### ISSUE TITLE
¿El sitio anterior?

### ISSUE THREAD

**Issue by str** [mxgxw/crowdvalidation#10]
http://contemosnosotros.org/ cambió recientemente. ¿Tienen un bkup del sitio anterior?

**Comment by salvadoresc** [comment]
podrias explicarte mejor? te referis al de las presidenciales? o a esta nueva version cual es el que cambio?

**Comment by str** [comment]
Correcto, al de presidenciales

**Comment by salvadoresc** [comment]
deberias poder verlo desde el branch original. el del 2015 se hizo un branch aparte

**Comment by salvadoresc** [comment]
el de presidenciales no esta en linea, pero dejame ver si podemos ponerlo en un subdomain ya que seria bueno que estuviera en linea. veo en tu perfil que estan haciendo un proyecto en guate (y)

**Comment by str** [comment]
Buscaba el sitio público para no instanciar el repositorio

**Comment by mxgxw** [comment]
Estuardo, el sitio viejo está bajo el branch master, el que está en el sitio está bajo el branch contemos2015.
